### ISSUE TITLE
feat(remote-swagger): provide a way to fetch secured swagger file

### ISSUE THREAD

**Issue by Nagogus** [zalando-incubator/hexo-theme-doc#38]
Currently it is not possible to fetch swagger file if it located under secured url e.g private github repository, enterprise github or just secured url.

As a solution I suggest to provide a way to define token to access urls. It can be defined via _config.yaml. 

E.g
```
authorization:
  auth_key_1: token1
  auth_key_2: token2
```

usage:
```
{% swagger_ui https://github.com/someprivate/swagger.yaml auth_key_1 %}
```

**Comment by rbarilani** [comment]
Hi @Nagogus after a discussion we decided that this feature must not be included in this tool but provided by something else. So we will like to close this issue.

### Why?

1. We consider dangerous to give the possibility to user to hard code credentials in their configuration file. 

2. As you mention the feature should work on private github repository, enterprise github or just secured url, since there are serveral ways to "secure" something and we cannot cover all of them, we will probably end-up with a solution that will be partial.

### Right-Away solutions if your specification is private:

* Use a proxy server that authenticate the request with whatever method you like to reach the protected endpoint

* Instead of using directly remote location, have a task that copies you secured spec to your fs and use those with the `swagger_ui` tag


@Nagogus WDYT?

**Comment by Nagogus** [comment]
@rbarilani I totally understand your concerns but I think the solutions you suggest are too "difficult" for getting swagger spec in documentation.

**Comment by rbarilani** [comment]
@Nagogus I was thinking something about HTTP Headers and to at least start with a global authentication mechanism that can be used with all your swagger specs....

### Config

```yaml
theme_config:
   swagger:
       http:
          headers:
              Authorization: Bearer {{env.AUTH_TOKEN}}
         # params:
         # token: {{env.AUTH_TOKEN}}
```
> where AUTH_TOKEN is an ENVIRONMENT variable

### Markdown page

```md
{% swagger_ui 'https://github.com/someprivate/swagger.yaml' %}
```

**Pro**: should be able to cover most common "Headers/Parameters based" authentication mechanism (Github with Personal access token or some other system with Basic Auth)
**Limitation**: you swagger specs must be available providing the same credentials.
**P0 requirement**: credentials must never being exposed through the generated output
